version: '3.8'
services:
  app:
    image: task-tracker-app:0.0.1
    container_name: task-tracker-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - hazelcast
      - management-center
    networks:
      - default

  db:
    image: postgres
    container_name: tasks_db
    environment:
      POSTGRES_USER: egor
      POSTGRES_PASSWORD: fusion
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    networks:
      - default

  hazelcast:
    image: hazelcast/hazelcast:latest
    ports:
      - "5701:5701"
    networks:
      - default

  management-center:
    image: hazelcast/management-center:latest
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
    ports:
      - "8081:8081"
    networks:
      - default

networks:
  default:
    name: tasks